-- PRACTICE PROBLEM 2
CREATE DATABASE IF NOT EXISTS SUBQUERIES;
USE SUBQUERIES;
CREATE TABLE STUDENT1(
ROLL_NO INT PRIMARY KEY,
NAME  VARCHAR(50),
MARKS INT
);
INSERT INTO STUDENT1
(ROLL_NO,NAME,MARKS)
VALUES
(101,'ANIL',78),
(102,'BHUMIKA',93),
(103,'CHETAN',85),
(104,'DHUR',96),
(105,'EMANUEL',92),
(106,'FARAH',82);

alter TABLE STUDENT1
ADD column TOWN VARCHAR(50);
SELECT * FROM STUDENT1;
UPDATE STUDENT1
SET TOWN = CASE
    WHEN ROLL_NO = 101 THEN 'PUNE'
    WHEN ROLL_NO = 102 THEN 'MUMBAI'
    WHEN ROLL_NO = 103 THEN 'PUNE'
    WHEN ROLL_NO = 104 THEN 'DELHI'
    WHEN ROLL_NO = 105 THEN 'DELHI'
    WHEN ROLL_NO = 106 THEN 'DELHI'
END
WHERE ROLL_NO IN (101, 102, 103, 104, 105, 106);
SELECT NAME 
FROM STUDENT1
WHERE TOWN ='DELHI';
SELECT MAX(MARKS),TOWN
FROM STUDENT1
WHERE TOWN ='DELHI'